/* E10 build plugin (design D5; contracts/sw-shell-cache.md §2): emits a
   self-contained, release-versioned `sw.js` into the vite output at
   `closeBundle`. No dependency — the strategy rules are inlined verbatim
   from `src/lib/pwa/strategy.js`, so the worker is a thin shell over
   tested logic and never imports at runtime. The BUILD_ID is a content
   hash of the built bundle (sorted file list + contents), never
   hand-maintained. */

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { precacheList } from '../src/lib/pwa/strategy.js';

const STRATEGY_MODULE = path.join('src', 'lib', 'pwa', 'strategy.js');

/**
 * Compose the service-worker source. Pure: same inputs, same bytes.
 *
 * @param {{
 *   buildId: string,
 *   precache: string[],
 *   strategySource: string,
 * }} parts
 * @returns {string} the complete sw.js source
 */
export function composeSw({ buildId, precache, strategySource }) {
  // The worker is a classic script, not a module: strip the strategy
  // module's export keywords and inline the bodies unchanged.
  const strategy = strategySource.replace(/^export\s+/gm, '');
  return `// GENERATED by web/plugins/sw-plugin.mjs at build time — do not edit.
// The shell cache is keyed to this release: one build id, one cache.
// Rules live in src/lib/pwa/strategy.js (tested there, inlined here).

${strategy}

const BUILD_ID = ${JSON.stringify(buildId)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};

async function precacheAll() {
  const cache = await caches.open(shellCacheName(BUILD_ID));
  // addAll is atomic: if one shell file fails, nothing is installed.
  await cache.addAll(PRECACHE);
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  // The precache owns the shell cache; nothing else is ever written to it.
  return fetch(request);
}

async function networkFirstShell(request) {
  try {
    return await fetch(request);
  } catch (err) {
    const cached = await caches.match('/index.html');
    if (cached) return cached;
    throw err;
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(precacheAll().then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(obsoleteCaches(names, BUILD_ID).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  const kind = classifyRequest(url.pathname, event.request.mode);
  if (kind === 'bypass') return;                       // /api/* and WS: one path, the app's
  if (kind === 'asset') { event.respondWith(cacheFirst(event.request)); return; }
  event.respondWith(networkFirstShell(event.request)); // navigation
});
`;
}

/**
 * The vite plugin. Registers `closeBundle` so `vite build` ends with
 * `dist/sw.js` alongside the hashed bundle it caches. Emits nothing when
 * the output directory has no files (never a worker over an empty build).
 *
 * @param {{ root?: string, outDir?: string }} [options] overrides for
 *   tests; in a real build root/outDir come from the resolved config
 * @returns {import('vite').Plugin} the plugin object
 */
export default function swPlugin(options = {}) {
  let root = options.root;
  let outDir = options.outDir;
  return {
    name: 'hireling-sw',
    configResolved(config) {
      if (!root) root = config.root;
      if (!outDir) outDir = config.build?.outDir ?? 'dist';
    },
    closeBundle() {
      if (!root) return;
      emitSw(root, outDir ?? 'dist');
    },
  };
}

function emitSw(root, outDir) {
  const distDir = path.resolve(root, outDir);
  if (!fs.existsSync(distDir)) return;
  const files = walk(distDir, distDir);
  if (files.length === 0) return; // nothing built; do not emit a lie
  const strategySource = fs.readFileSync(path.resolve(root, STRATEGY_MODULE), 'utf8');
  const source = composeSw({
    buildId: buildIdFor(files, distDir),
    precache: precacheList(files),
    strategySource,
  });
  fs.writeFileSync(path.join(distDir, 'sw.js'), source);
}

/** Relative posix paths of every file under dist, except a stale sw.js —
    the worker never hashes itself. */
function walk(dir, base) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const rel = path.relative(base, abs).split(path.sep).join('/');
    if (entry.isDirectory()) out.push(...walk(abs, base));
    else if (rel !== 'sw.js') out.push(rel);
  }
  return out.sort();
}

/** Content hash of the built bundle: every file's path and bytes, in
    sorted order. Same build ⇒ same id; any changed byte ⇒ new release. */
function buildIdFor(files, distDir) {
  const hash = crypto.createHash('sha256');
  for (const file of files) {
    hash.update(file);
    hash.update('\0');
    hash.update(fs.readFileSync(path.join(distDir, file)));
  }
  return hash.digest('hex').slice(0, 16);
}
