//! HTTP shell: router, middleware, and the server loop.
//!
//! Shell layer — framework plumbing only. Logic with rules behind it (the
//! health payload's contract, settings parsing) lives in pure modules; this
//! file wires them into axum.

use std::net::SocketAddr;
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;

use anyhow::Context as _;
use axum::extract::Request;
use axum::http::HeaderName;
use axum::routing::get;
use axum::routing::post;
use axum::{Json, Router};
use sqlx::PgPool;
use tower_http::request_id::{MakeRequestUuid, PropagateRequestIdLayer, SetRequestIdLayer};
use tower_http::services::{ServeDir, ServeFile};
use tower_http::trace::{DefaultOnResponse, TraceLayer};

use crate::auth::AuthState;
use crate::auth::handlers;
use crate::auth::middleware;
use crate::config::Settings;
use crate::health::{HealthPayload, health_payload};

/// Header carrying the correlation ID — propagated when the caller sends one,
/// generated by the server otherwise.
pub(crate) const REQUEST_ID_HEADER: HeaderName = HeaderName::from_static("x-request-id");

/// How long shutdown waits for in-flight requests before the process gives up
/// on draining and exits anyway.
const DRAIN_TIMEOUT: Duration = Duration::from_secs(10);

/// The declarative `/api` route list — the single source the ownership
/// matrix test iterates, so "zero untested endpoints" cannot drift. The
/// mount code below must keep mounting exactly these routes inside the
/// protected nest; the router tests probe every listed path for its guard.
#[cfg_attr(
    not(test),
    expect(dead_code, reason = "consumed by the router-test suite")
)]
pub(crate) struct ApiRoute {
    pub method: &'static str,
    pub path: &'static str,
    /// Whether the route can mutate state — every write route must carry an
    /// explicit authorization rule; absence of a rule is a denial (spec FR-7).
    pub writes: bool,
}

#[cfg_attr(
    not(test),
    expect(dead_code, reason = "consumed by the router-test suite")
)]
pub(crate) const API_ROUTES: &[ApiRoute] = &[ApiRoute {
    method: "GET",
    path: "/api/me",
    writes: false,
}];

/// Build the application router.
///
/// Explicit routes win over the fallback, so `/healthz` answers even when the
/// frontend bundle is missing. Everything else is served from `static_dir`;
/// paths that match no file get the shell page so client-side routing works.
///
/// Auth layers on the protected nest, innermost first: `gm_read_only`, then
/// `require_auth`, with `resolve_session` wrapping the whole `/api` nest —
/// see `specs/003-authentik-oidc/design.md` §4. The public set inside `/api`
/// is exactly the auth legs (plus, in debug builds, the dev-session route).
pub fn router(auth: Arc<AuthState>, static_dir: &Path) -> Router {
    // `.fallback`, not `.not_found_service`: the latter wraps the fallback in
    // a forced 404 status, which serves the shell page marked as an error.
    let frontend =
        ServeDir::new(static_dir).fallback(ServeFile::new(static_dir.join("index.html")));

    let protected = Router::new().route("/me", get(handlers::me));

    // Public inside the nest: the auth legs. Logout is session-aware but
    // idempotent, so it needs no guard of its own.
    let legs = Router::new()
        .route("/auth/login", get(handlers::login))
        .route("/auth/callback", get(handlers::callback))
        .route("/auth/logout", post(handlers::logout));

    #[cfg(debug_assertions)]
    let legs = legs.route(
        "/dev/session",
        post(handlers::dev::create).get(handlers::dev::picker),
    );

    let api = protected
        .layer(axum::middleware::from_fn_with_state(
            std::sync::Arc::clone(&auth),
            middleware::gm_read_only,
        ))
        .layer(axum::middleware::from_fn_with_state(
            std::sync::Arc::clone(&auth),
            middleware::require_auth,
        ))
        .merge(legs)
        .layer(axum::middleware::from_fn_with_state(
            std::sync::Arc::clone(&auth),
            middleware::resolve_session,
        ))
        .with_state(auth);

    // Layer order reads bottom-up on the request path: the request-id setter
    // runs first (so the header exists), propagation copies it to the
    // response, and the trace span can then record it on every log line.
    Router::new()
        .route("/healthz", get(health))
        .nest("/api", api)
        .fallback_service(frontend)
        .layer(
            TraceLayer::new_for_http()
                .make_span_with(|request: &Request| {
                    let request_id = request
                        .headers()
                        .get(REQUEST_ID_HEADER)
                        .and_then(|value| value.to_str().ok())
                        .unwrap_or("unknown");
                    tracing::info_span!(
                        "request",
                        method = %request.method(),
                        path = %request.uri().path(),
                        request_id,
                    )
                })
                // One line per request at info — low-traffic app, and the
                // correlation ID on that line is the trace handle.
                .on_response(DefaultOnResponse::new().level(tracing::Level::INFO)),
        )
        .layer(PropagateRequestIdLayer::new(REQUEST_ID_HEADER))
        .layer(SetRequestIdLayer::new(REQUEST_ID_HEADER, MakeRequestUuid))
}

/// `GET /healthz` — dependency-free on purpose: it answers even when Postgres
/// (or anything else) is down, so monitors can tell "process dead" apart from
/// "dependency dead".
async fn health() -> Json<HealthPayload> {
    Json(health_payload())
}

/// Serve until a termination signal arrives, then drain in-flight requests
/// within [`DRAIN_TIMEOUT`].
///
/// The pool arrives already connected and migrated; this turns it into the
/// auth state the router runs on.
///
/// # Errors
///
/// Returns an error if the port cannot be bound or the server fails.
pub async fn serve(settings: &Settings, pool: PgPool) -> anyhow::Result<()> {
    let address = SocketAddr::from(([0, 0, 0, 0], settings.port));
    let listener = tokio::net::TcpListener::bind(address)
        .await
        .with_context(|| format!("failed to bind {address}"))?;

    let auth = AuthState::new(pool, &settings.auth)?;

    tracing::info!(
        port = settings.port,
        static_dir = %settings.static_dir.display(),
        "serving"
    );

    let server = axum::serve(listener, router(auth, &settings.static_dir))
        .with_graceful_shutdown(shutdown_signal());

    tokio::select! {
        result = server => {
            result.context("server error")?;
            tracing::info!("in-flight requests drained; exiting");
            Ok(())
        }
        () = force_exit_after_drain_window() => {
            tracing::warn!(
                drain_timeout = ?DRAIN_TIMEOUT,
                "shutdown drain exceeded; exiting with requests still in flight"
            );
            Ok(())
        }
    }
}

/// Complete when the drain window expires after a termination signal.
async fn force_exit_after_drain_window() {
    shutdown_signal().await;
    tokio::time::sleep(DRAIN_TIMEOUT).await;
}

/// Complete on SIGINT or SIGTERM, whichever arrives first.
///
/// Registered once per caller on purpose — the server drain and the
/// force-exit timer each hold their own registration so one signal starts both.
/// Deliberately silent: the outcome (drained or forced) is what gets logged.
async fn shutdown_signal() {
    let mut terminate =
        match tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()) {
            Ok(signal) => signal,
            Err(sigterm_err) => {
                tracing::error!(error = %sigterm_err, "failed to install SIGTERM handler");
                if let Err(sigint_err) = tokio::signal::ctrl_c().await {
                    tracing::error!(error = %sigint_err, "failed to listen for SIGINT");
                }
                return;
            }
        };

    tokio::select! {
        result = tokio::signal::ctrl_c() => {
            if let Err(sigint_err) = result {
                tracing::error!(error = %sigint_err, "failed to listen for SIGINT");
            }
        }
        _received = terminate.recv() => {}
    }
}

#[cfg(test)]
#[path = "tests/http.rs"]
mod tests;
