//! HTTP shell: router, middleware, and the server loop.
//!
//! Shell layer — framework plumbing only. Logic with rules behind it (the
//! health payload's contract, settings parsing) lives in pure modules; this
//! file wires them into axum.

use std::net::SocketAddr;
use std::path::Path;
use std::time::Duration;

use anyhow::Context as _;
use axum::extract::Request;
use axum::http::HeaderName;
use axum::routing::get;
use axum::{Json, Router};
use tower_http::request_id::{MakeRequestUuid, PropagateRequestIdLayer, SetRequestIdLayer};
use tower_http::services::{ServeDir, ServeFile};
use tower_http::trace::{DefaultOnResponse, TraceLayer};

use crate::config::Settings;
use crate::health::{HealthPayload, health_payload};

/// Header carrying the correlation ID — propagated when the caller sends one,
/// generated by the server otherwise.
const REQUEST_ID_HEADER: HeaderName = HeaderName::from_static("x-request-id");

/// How long shutdown waits for in-flight requests before the process gives up
/// on draining and exits anyway.
const DRAIN_TIMEOUT: Duration = Duration::from_secs(10);

/// Build the application router.
///
/// Explicit routes win over the fallback, so `/healthz` answers even when the
/// frontend bundle is missing. Everything else is served from `static_dir`;
/// paths that match no file get the shell page so client-side routing works.
pub fn router(static_dir: &Path) -> Router {
    let frontend =
        ServeDir::new(static_dir).not_found_service(ServeFile::new(static_dir.join("index.html")));

    // Layer order reads bottom-up on the request path: the request-id setter
    // runs first (so the header exists), propagation copies it to the
    // response, and the trace span can then record it on every log line.
    Router::new()
        .route("/healthz", get(health))
        .fallback_service(frontend)
        .layer(
            TraceLayer::new_for_http()
                .make_span_with(|request: &Request| {
                    let request_id = request
                        .headers()
                        .get(REQUEST_ID_HEADER)
                        .and_then(|value| value.to_str().ok())
                        .unwrap_or("unknown");
                    tracing::info_span!(
                        "request",
                        method = %request.method(),
                        path = %request.uri().path(),
                        request_id,
                    )
                })
                // One line per request at info — low-traffic app, and the
                // correlation ID on that line is the trace handle.
                .on_response(DefaultOnResponse::new().level(tracing::Level::INFO)),
        )
        .layer(PropagateRequestIdLayer::new(REQUEST_ID_HEADER))
        .layer(SetRequestIdLayer::new(REQUEST_ID_HEADER, MakeRequestUuid))
}

/// `GET /healthz` — dependency-free on purpose: it answers even when Postgres
/// (or anything else) is down, so monitors can tell "process dead" apart from
/// "dependency dead".
async fn health() -> Json<HealthPayload> {
    Json(health_payload())
}

/// Serve until a termination signal arrives, then drain in-flight requests
/// within [`DRAIN_TIMEOUT`].
///
/// # Errors
///
/// Returns an error if the port cannot be bound or the server fails.
pub async fn serve(settings: &Settings) -> anyhow::Result<()> {
    let address = SocketAddr::from(([0, 0, 0, 0], settings.port));
    let listener = tokio::net::TcpListener::bind(address)
        .await
        .with_context(|| format!("failed to bind {address}"))?;

    tracing::info!(
        port = settings.port,
        static_dir = %settings.static_dir.display(),
        "serving"
    );

    let server = axum::serve(listener, router(&settings.static_dir))
        .with_graceful_shutdown(shutdown_signal());

    tokio::select! {
        result = server => {
            result.context("server error")?;
            tracing::info!("in-flight requests drained; exiting");
            Ok(())
        }
        () = force_exit_after_drain_window() => {
            tracing::warn!(
                drain_timeout = ?DRAIN_TIMEOUT,
                "shutdown drain exceeded; exiting with requests still in flight"
            );
            Ok(())
        }
    }
}

/// Complete when the drain window expires after a termination signal.
async fn force_exit_after_drain_window() {
    shutdown_signal().await;
    tokio::time::sleep(DRAIN_TIMEOUT).await;
}

/// Complete on SIGINT or SIGTERM, whichever arrives first.
///
/// Registered once per caller on purpose — the server drain and the
/// force-exit timer each hold their own registration so one signal starts both.
/// Deliberately silent: the outcome (drained or forced) is what gets logged.
async fn shutdown_signal() {
    let mut terminate =
        match tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()) {
            Ok(signal) => signal,
            Err(sigterm_err) => {
                tracing::error!(error = %sigterm_err, "failed to install SIGTERM handler");
                if let Err(sigint_err) = tokio::signal::ctrl_c().await {
                    tracing::error!(error = %sigint_err, "failed to listen for SIGINT");
                }
                return;
            }
        };

    tokio::select! {
        result = tokio::signal::ctrl_c() => {
            if let Err(sigint_err) = result {
                tracing::error!(error = %sigint_err, "failed to listen for SIGINT");
            }
        }
        _received = terminate.recv() => {}
    }
}
