import { afterEach, test } from 'vitest';
import assert from 'node:assert/strict';

import { render, cleanup } from '@testing-library/svelte';
import { get } from 'svelte/store';

import { createSync } from '../../src/lib/sync/index.js';
import { createSheetState } from '../../src/lib/sheet/state.js';
import { fakeClock, mockSockets, fakeStorage } from '../sync/fakes.js';
import StatsPane from '../../src/lib/sheet/components/StatsPane.svelte';
import StrikesPane from '../../src/lib/sheet/components/StrikesPane.svelte';
import { partitionSkills } from '../../src/lib/engine/partition.js';

// The adapter swap's acceptance gate: the reference character (Lorum Ipsum,
// level 3, level_adjust = 0) renders BYTE-IDENTICALLY to the pre-swap
// values `web/tests/engine/base.test.js` pinned. One side of the comparison
// is the engine-output fixture — generated by the REAL extractor + compute
// (specs/008 design D3's golden math) over the same reference export the
// old base math consumed; the other side is this pinned table.

import engine from '../data/engine_output_reference.json';
import baseSheet from '../data/base_sheet_reference.json';

afterEach(cleanup);

test('render_base carries the pre-swap ceilings and level inputs', () => {
  assert.equal(engine.render_base.level, 3);
  assert.equal(engine.render_base.hp_max, 32, '8 + (6 + CON 2) × 3 — the prototype formula');
  assert.equal(engine.render_base.focus_max, 1);
  assert.equal(engine.render_base.hero_max, 3);
  assert.equal(engine.render_base.cantrip_rank, 2, '⌈3 / 2⌉');
  assert.deepEqual(engine.render_base.attributes, {
    str: -1, dex: 1, con: 2, int: 4, wis: 0, cha: 3,
  });
});

test('the pinned globals: AC, saves, perception, speed, class DC', () => {
  const d = engine.derived;
  assert.equal(d.ac.total, 16);
  assert.equal(d.fort.total, 7);
  assert.equal(d.ref.total, 6);
  assert.equal(d.will.total, 7);
  assert.equal(d.perception.total, 5);
  assert.equal(d.speed.total, 25);
  assert.equal(d.class_dc.total, 19);
});

test('the pinned skills: all 16 core rows and both lores, totals and rank letters', () => {
  const expected = {
    acrobatics: 1, athletics: -1, arcana: 9, crafting: 4, deception: 10,
    diplomacy: 8, intimidation: 3, medicine: 0, nature: 0, occultism: 9,
    performance: 3, religion: 0, society: 9, stealth: 6, survival: 0,
    thievery: 6,
  };
  const totalOf = (name) =>
    engine.derived.skills.find((skill) => skill.name === name)?.total;
  for (const [name, total] of Object.entries(expected)) {
    assert.equal(totalOf(name), total, `${name}`);
  }
  const { lores } = partitionSkills(engine.derived.skills);
  assert.deepEqual(
    lores.map((lore) => [lore.label, lore.total, lore.rank]),
    [
      ['Underworld Lore', 9, 2],
      ['Mror Holds History Lore', 11, 4],
    ],
    'the pre-swap row labels, from the wire\u2019s display names',
  );
});

test('the pinned strikes and casters, display fields included', () => {
  const [staff, fist] = engine.derived.strikes;
  assert.deepEqual(
    [staff.label, staff.attack.total, staff.map, staff.damage_expr, staff.damage_type_name],
    ['Staff', 4, 5, 'd4−1', 'bludgeoning'],
  );
  assert.deepEqual(fist.label, 'Fist');
  assert.equal(fist.attack.total, 6);
  assert.equal(fist.map, 4, 'agile: −4/−8');
  assert.equal(fist.damage_expr, 'd4−1', 'd4 + str −1');
  assert.deepEqual(staff.traits, ['Monk', 'Two-Hand d8']);

  const [wizard, gnome] = engine.derived.casters;
  assert.deepEqual(
    [wizard.caster_key, wizard.spell_attack.total, wizard.spell_dc.total, wizard.innate],
    ['Wizard', 9, 19, false],
  );
  assert.deepEqual(
    [gnome.caster_key, gnome.spell_attack.total, gnome.spell_dc.total, gnome.innate],
    ['Wellspring Gnome', 8, 18, true],
    'the innate flag rides the wire',
  );
});

test('the stats pane renders the pinned numbers from the wire fixture', () => {
  const body = render(StatsPane, {
    props: {
      view: engine,
      baseSheet,
      hp: { value: 20, pending: false },
      temp: { value: 0, pending: false },
      money: { value: { pp: 0, gp: 24, sp: 2, cp: 4 }, pending: false },
      focusCurrent: { value: 0, pending: false },
      focusMax: engine.render_base.focus_max,
      heroPoints: { value: 1, pending: false },
      heroMax: engine.render_base.hero_max,
    },
  }).container.innerHTML;
  for (const pinned of [
    'Armor Class', '+7', '+6', 'Class DC', '19', 'Perception', '+5',
    'Thievery', 'Underworld Lore', 'Mror Holds History Lore', '+9', '+11',
  ]) {
    assert.match(body, new RegExp(pinned.replace(/[+]/g, '\\+')), pinned);
  }
});

test('the strikes pane renders the pinned rows from the wire fixture', () => {
  const body = render(StrikesPane, { props: { view: engine } }).container.innerHTML;
  assert.match(body, /Staff/);
  assert.match(body, /atk \+4/);
  assert.match(body, /MAP −5 \/ −10/);
  assert.match(body, /d4−1/);
  assert.match(body, /Fist/);
  assert.match(body, /atk \+6/);
  assert.match(body, /MAP −4 \/ −8/, 'agile');
});

// The identity claim must arrive through the PRODUCTION path — snapshot
// frame → sync surface → the engine seam → `createSheetState` — or it
// pins a fixture against a table and never enters the seam (review F4).
// This is the same pinned table, routed.
test('the identity rides the production path: snapshot → sync → derive → state', () => {
  const clock = fakeClock();
  const mocks = mockSockets();
  const sync = createSync({
    url: 'ws://test/party/1',
    storage: fakeStorage(),
    accountSub: 'sub-a',
    socketFactory: mocks.factory,
    rng: () => 1,
    now: clock.now,
    timers: clock.timers,
    idFactory: () => 'op-1',
  });
  const state = createSheetState({
    sync,
    character: {
      character: { id: 7, name: baseSheet.identity.name },
      base_sheet: baseSheet,
      vitals: { hp: 20, temp_hp: 0, money_pp: 0, money_gp: 24, money_sp: 2, money_cp: 4, level_adjust: 0, focus_current: 0, hero_points: 1, daily: { staff_charge_rank: 3, staff_spent: 0, drain_used: false } },
      slots: [],
      inventory: [],
      item_bulk: {},
    },
  });

  assert.equal(get(state.view), null, 'nothing before the wire');
  state.connect();
  mocks.sockets[0].open();
  mocks.sockets[0].message(
    JSON.stringify({ t: 'snapshot', fields: [], derived: [engine], snapshot_bytes: 42 }),
  );

  const view = get(state.view);
  assert.ok(view, 'the seam surfaced the snapshot\'s engine output');
  assert.equal(view, sync.derived(7), 'verbatim: the sync surface\'s own answer object, not a recomputed copy');
  assert.equal(view.render_base.hp_max, 32, 'pinned hp max, through the path');
  assert.equal(view.derived.ac.total, 16, 'pinned AC, through the path');
  assert.equal(view.derived.fort.total, 7);
  assert.equal(view.derived.skills.find((s) => s.name === 'lore:mror_holds_history').total, 11);
  assert.equal(get(state.hpMax), 32, 'the ceiling store reads the same output');
});
