/* global URL */
import test from 'node:test';
import assert from 'node:assert/strict';

import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { render } from 'svelte/server';

import StatsPane from '../../src/lib/sheet/components/StatsPane.svelte';
import StrikesPane from '../../src/lib/sheet/components/StrikesPane.svelte';
import { partitionSkills } from '../../src/lib/engine/partition.js';

// The adapter swap's acceptance gate: the reference character (Lorum Ipsum,
// level 3, level_adjust = 0) renders BYTE-IDENTICALLY to the pre-swap
// values `web/tests/engine/base.test.js` pinned. One side of the comparison
// is the engine-output fixture — generated by the REAL extractor + compute
// (specs/008 design D3's golden math) over the same reference export the
// old base math consumed; the other side is this pinned table.

const ENGINE_PATH = fileURLToPath(new URL('../data/engine_output_reference.json', import.meta.url));
const engine = JSON.parse(await readFile(ENGINE_PATH, 'utf8'));
const SHEET_PATH = fileURLToPath(new URL('../data/base_sheet_reference.json', import.meta.url));
const baseSheet = JSON.parse(await readFile(SHEET_PATH, 'utf8'));

test('render_base carries the pre-swap ceilings and level inputs', () => {
  assert.equal(engine.render_base.level, 3);
  assert.equal(engine.render_base.hp_max, 32, '8 + (6 + CON 2) × 3 — the prototype formula');
  assert.equal(engine.render_base.focus_max, 1);
  assert.equal(engine.render_base.hero_max, 3);
  assert.equal(engine.render_base.cantrip_rank, 2, '⌈3 / 2⌉');
  assert.deepEqual(engine.render_base.attributes, {
    str: -1, dex: 1, con: 2, int: 4, wis: 0, cha: 3,
  });
});

test('the pinned globals: AC, saves, perception, speed, class DC', () => {
  const d = engine.derived;
  assert.equal(d.ac.total, 16);
  assert.equal(d.fort.total, 7);
  assert.equal(d.ref.total, 6);
  assert.equal(d.will.total, 7);
  assert.equal(d.perception.total, 5);
  assert.equal(d.speed.total, 25);
  assert.equal(d.class_dc.total, 19);
});

test('the pinned skills: all 16 core rows and both lores, totals and rank letters', () => {
  const expected = {
    acrobatics: 1, athletics: -1, arcana: 9, crafting: 4, deception: 10,
    diplomacy: 8, intimidation: 3, medicine: 0, nature: 0, occultism: 9,
    performance: 3, religion: 0, society: 9, stealth: 6, survival: 0,
    thievery: 6,
  };
  const totalOf = (name) =>
    engine.derived.skills.find((skill) => skill.name === name)?.total;
  for (const [name, total] of Object.entries(expected)) {
    assert.equal(totalOf(name), total, `${name}`);
  }
  const { lores } = partitionSkills(engine.derived.skills);
  assert.deepEqual(
    lores.map((lore) => [lore.label, lore.total, lore.rank]),
    [
      ['Underworld Lore', 9, 2],
      ['Mror Holds History Lore', 11, 4],
    ],
    'the pre-swap row labels, from the wire\u2019s display names',
  );
});

test('the pinned strikes and casters, display fields included', () => {
  const [staff, fist] = engine.derived.strikes;
  assert.deepEqual(
    [staff.label, staff.attack.total, staff.map, staff.damage_expr, staff.damage_type_name],
    ['Staff', 4, 5, 'd4−1', 'bludgeoning'],
  );
  assert.deepEqual(fist.label, 'Fist');
  assert.equal(fist.attack.total, 6);
  assert.equal(fist.map, 4, 'agile: −4/−8');
  assert.equal(fist.damage_expr, 'd4−1', 'd4 + str −1');
  assert.deepEqual(staff.traits, ['Monk', 'Two-Hand d8']);

  const [wizard, gnome] = engine.derived.casters;
  assert.deepEqual(
    [wizard.caster_key, wizard.spell_attack.total, wizard.spell_dc.total, wizard.innate],
    ['Wizard', 9, 19, false],
  );
  assert.deepEqual(
    [gnome.caster_key, gnome.spell_attack.total, gnome.spell_dc.total, gnome.innate],
    ['Wellspring Gnome', 8, 18, true],
    'the innate flag rides the wire',
  );
});

test('the stats pane renders the pinned numbers from the wire fixture', () => {
  const { body } = render(StatsPane, {
    props: {
      view: engine,
      baseSheet,
      hp: { value: 20, pending: false },
      temp: { value: 0, pending: false },
      money: { value: { pp: 0, gp: 24, sp: 2, cp: 4 }, pending: false },
      focusCurrent: { value: 0, pending: false },
      focusMax: engine.render_base.focus_max,
      heroPoints: { value: 1, pending: false },
      heroMax: engine.render_base.hero_max,
    },
  });
  for (const pinned of [
    'Armor Class', '+7', '+6', 'Class DC', '19', 'Perception', '+5',
    'Thievery', 'Underworld Lore', 'Mror Holds History Lore', '+9', '+11',
  ]) {
    assert.match(body, new RegExp(pinned.replace(/[+]/g, '\\+')), pinned);
  }
});

test('the strikes pane renders the pinned rows from the wire fixture', () => {
  const { body } = render(StrikesPane, { props: { view: engine } });
  assert.match(body, /Staff/);
  assert.match(body, /atk \+4/);
  assert.match(body, /MAP −5 \/ −10/);
  assert.match(body, /d4−1/);
  assert.match(body, /Fist/);
  assert.match(body, /atk \+6/);
  assert.match(body, /MAP −4 \/ −8/, 'agile');
});
